### ISSUE TITLE
Easy Effects fails to load Razor Surround impulse

### ISSUE THREAD

**Issue by whitedeviltakamachinanoha-oss** [JackHack96/PulseEffects-Presets#53]
I reinstalled Linux Mint, and now Easy Effects shows me the following message when loading my preset:

**"Failed to load the Razor Surround ((48k Z-Edition)) 2.Stereo +20 bass impulse. The Convolver is in passthrough mode."**

It worked on my old Linux Mint installation where I added Pipewire manually, but I don't know how I got it to work then. My laptop is an Acer Predator with an Realtek sound card (on Windows, it had the Windows Sonic option) that _should_ be capable of surround sound. My headphones are the OneOdio Pro 10. Do you know what I can do to make the Razor Impulse work again? Or is there a source to download the impulse response separately maybe?

**Comment by JackHack96** [comment]
I've noticed that in the installation script I was not checking the existence of a folder, so I pushed a fix. Can you try it?

In case, you can download the IRS manually by downloading the repo and put them inside the "irs" folder in the configuration files of the app (the position depends on the installation method).

What I advise is to use Flatpak as an installation method.
After the installation, it should appear like this:
<img width="1204" height="814" alt="Image" src="https://github.com/user-attachments/assets/2b1ce31e-3ce0-443b-975c-cd642e15a95f" />

**Comment by whitedeviltakamachinanoha-oss** [comment]
It worked. Thanks a lot!

I actually tweaked the Perfect EQ and Bass Boost preset with other effects for my headphones. If I wanted to export my preset to another machine, would there be a way for me to manually install the Razor Surround impulse response or is that only possible through your script?

**Comment by io-qar** [comment]
It looks like the fix still doesn't work. The convoler says "Convoler impuse is not set".

**Comment by JackHack96** [comment]
> It looks like the fix still doesn't work. The convoler says "Convoler impuse is not set".

Damn :/
Could you tell me the way you installed EasyEffects (Flatpak, DEB, others?)
Also, could you please re-run the installation command using the debug flag `-x`? Like this:
```
bash -x -c "$(curl -fsSL https://raw.githubusercontent.com/JackHack96/PulseEffects-Presets/master/install.sh)"
```
This will produce a lot of output compared to the normal run, if you can post that it should help me trying to reproduce that bug.
Thanks.

**Comment by io-qar** [comment]
@JackHack96 Interesting, now the convoler works correctly.. The impulse is there. I'm running the Flatpak version. Here is the output after the installation of all presets:
```sh
bash -x -c "$(curl -fsSL https://raw.githubusercontent.com/JackHack96/PulseEffects-Presets/master/install.sh)"
+ GIT_REPOSITORY=https://raw.githubusercontent.com/JackHack96/EasyEffects-Presets/master
+ check_installation
+ command -v flatpak
+ flatpak list
+ grep -q com.github.wwmm.easyeffects
+ PRESETS_DIRECTORY=/home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects
+ mkdir -p /home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects
+ check_impulse_response_directory
+ '[' '!' -d /home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/irs ']'
+ '[' '!' -d /home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output ']'
+ mkdir /home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output
+ install_menu
+ echo 'Please select an option for presets installation (Default=1)'
Please select an option for presets installation (Default=1)
+ echo '1) Install all presets'
1) Install all presets
+ echo '2) Install Perfect EQ preset'
2) Install Perfect EQ preset
+ echo '3) Install all bass boosting presets'
3) Install all bass boosting presets
+ echo '4) Install Advanced Auto Gain'
4) Install Advanced Auto Gain
+ echo '5) Install Laptop speaker preset'
5) Install Laptop speaker preset
+ echo '6) Install loudness + autogain laptop preset'
6) Install loudness + autogain laptop preset
+ read_choice
+ :
+ read -r CHOICE
1
+ '[' -z 1 ']'
+ [[ 1 =~ ^[1-6]+$ ]]
+ break
+ install_presets
+ case $CHOICE in
+ echo 'Installing Bass Enhancing + Perfect EQ preset...'
Installing Bass Enhancing + Perfect EQ preset...
+ curl https://raw.githubusercontent.com/JackHack96/EasyEffects-Presets/master/Bass%20Enhancing%20%2B%20Perfect%20EQ.json --output '/home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output/Bass Enhancing + Perfect EQ.json' --silent
+ echo 'Installing impulse response files...'
Installing impulse response files...
+ curl 'https://raw.githubusercontent.com/JackHack96/EasyEffects-Presets/master/irs/Dolby%20ATMOS%20((128K%20MP3))%201.Default.irs' --output '/home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/irs/Dolby ATMOS ((128K MP3)) 1.Default.irs' --silent
+ curl 'https://raw.githubusercontent.com/JackHack96/EasyEffects-Presets/master/irs/MaxxAudio%20Pro%20((128K%20MP3))%204.Music%20w%20MaxxSpace.irs' --output '/home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/irs/MaxxAudio Pro ((128K MP3)) 4.Music w MaxxSpace.irs' --silent
+ curl 'https://raw.githubusercontent.com/JackHack96/EasyEffects-Presets/master/irs/Razor%20Surround%20((48k%20Z-Edition))%202.Stereo%20+20%20bass.irs' --output '/home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/irs/Razor Surround ((48k Z-Edition)) 2.Stereo +20 bass.irs' --silent
+ curl 'https://raw.githubusercontent.com/JackHack96/EasyEffects-Presets/master/irs/Accudio%20((48kHz%20Z.E.))%20Earpods%20HIFI.irs' --output '/home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/irs/Accudio ((48kHz Z.E.)) Earpods HIFI.irs' --silent
+ curl 'https://raw.githubusercontent.com/JackHack96/EasyEffects-Presets/master/irs/Accudio%20((48kHz%20Z.E.))%20MDR-E9LP%20HIFI.irs' --output '/home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/irs/Accudio ((48kHz Z.E.)) MDR-E9LP HIFI.irs' --silent
+ curl 'https://raw.githubusercontent.com/JackHack96/EasyEffects-Presets/master/irs/Accudio%20((48kHz%20Z.E.))%20MDR-E9LP%20SM%20SRH940.irs' --output '/home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/irs/Accudio ((48kHz Z.E.)) MDR-E9LP SM SRH940.irs' --silent
+ curl 'https://raw.githubusercontent.com/JackHack96/EasyEffects-Presets/master/irs/Accudio%20((48kHz%20Z.E.))%20MDR-E9LP%20SM%20XBA3.irs' --output '/home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/irs/Accudio ((48kHz Z.E.)) MDR-E9LP SM XBA3.irs' --silent
+ curl 'https://raw.githubusercontent.com/JackHack96/EasyEffects-Presets/master/irs/Accudio%20((48kHz%20Z.E.))%20MDR-E9LP%20SM%20beyerT1.irs' --output '/home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/irs/Accudio ((48kHz Z.E.)) MDR-E9LP SM beyerT1.irs' --silent
+ curl 'https://raw.githubusercontent.com/JackHack96/EasyEffects-Presets/master/irs/Accudio%20((48kHz%20Z.E.))%20MDR-XB500%20HIFI.irs' --output '/home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/irs/Accudio ((48kHz Z.E.)) MDR-XB500 HIFI.irs' --silent
+ curl 'https://raw.githubusercontent.com/JackHack96/EasyEffects-Presets/master/irs/Accudio%20((48kHz%20Z.E.))%20XBA-H3%20HIFI.irs' --output '/home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/irs/Accudio ((48kHz Z.E.)) XBA-H3 HIFI.irs' --silent
+ curl 'https://raw.githubusercontent.com/JackHack96/EasyEffects-Presets/master/irs/Accudio%20((48kHz%20Z.E.))%20XBA-H3%20SM%20SRH940.irs' --output '/home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/irs/Accudio ((48kHz Z.E.)) XBA-H3 SM SRH940.irs' --silent
+ curl 'https://raw.githubusercontent.com/JackHack96/EasyEffects-Presets/master/irs/Accudio%20((48kHz%20Z.E.))%20XBA-H3%20SM%20XBA4.irs' --output '/home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/irs/Accudio ((48kHz Z.E.)) XBA-H3 SM XBA4.irs' --silent
+ curl 'https://raw.githubusercontent.com/JackHack96/EasyEffects-Presets/master/irs/Accudio%20((48kHz%20Z.E.))%20XBA-H3%20SM%20beyerT1.irs' --output '/home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/irs/Accudio ((48kHz Z.E.)) XBA-H3 SM beyerT1.irs' --silent
+ curl 'https://raw.githubusercontent.com/JackHack96/EasyEffects-Presets/master/irs/Creative%20X-Fi%20((Z-Edition))%20Crystalizer%2010%20%2B%20Expand%2010.irs' --output '/home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/irs/Creative X-Fi ((Z-Edition)) Crystalizer 10 + Expand 10.irs' --silent
+ curl 'https://raw.githubusercontent.com/JackHack96/EasyEffects-Presets/master/irs/HTC%20Beats%20Audio%20((Z-Edition)).irs' --output '/home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/irs/HTC Beats Audio ((Z-Edition)).irs' --silent
+ curl 'https://raw.githubusercontent.com/JackHack96/EasyEffects-Presets/master/irs/Waves%20MaxxAudio%20((Z-Edition))%20AudioWizard%201.Music.irs' --output '/home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/irs/Waves MaxxAudio ((Z-Edition)) AudioWizard 1.Music.irs' --silent
+ echo 'Installing Boosted preset...'
Installing Boosted preset...
+ curl https://raw.githubusercontent.com/JackHack96/EasyEffects-Presets/master/Boosted.json --output /home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output/Boosted.json --silent
+ echo 'Installing Perfect EQ preset...'
Installing Perfect EQ preset...
+ curl https://raw.githubusercontent.com/JackHack96/EasyEffects-Presets/master/Perfect%20EQ.json --output '/home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output/Perfect EQ.json' --silent
+ curl https://raw.githubusercontent.com/JackHack96/EasyEffects-Presets/master/Bass%20Boosted.json --output '/home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output/Bass Boosted.json' --silent
+ sed -i 's|<PRESETS_DIRECTORY>|/home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects|g' '/home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output/Bass Boosted.json'
+ echo 'Installing Advanced Auto Gain...'
Installing Advanced Auto Gain...
+ curl https://raw.githubusercontent.com/JackHack96/EasyEffects-Presets/master/Advanced%20Auto%20Gain.json --output '/home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output/Advanced Auto Gain.json' --silent
+ echo 'Installing Laptop preset...'
Installing Laptop preset...
+ curl https://raw.githubusercontent.com/Digitalone1/EasyEffects-Presets/master/LoudnessEqualizer.json --output /home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output/Laptop.json --silent
+ echo 'Installing loudness + autogain laptop preset...'
Installing loudness + autogain laptop preset...
+ curl https://raw.githubusercontent.com/JackHack96/EasyEffects-Presets/master/Loudness%2BAutogain.json --output /home/koro/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output/Loudness+Autogain.json --silent
```

**Comment by whitedeviltakamachinanoha-oss** [comment]
Btw, what exactly does the Razor Surround impulse do?

**Comment by JackHack96** [comment]
@io-qar Ok the output is actually correct and the script actually installed the things in the right places. So yeah everything should just work xD
I think that if it fails again, it would be interesting to see the logs of the app (like running the application using `flatpak run` command on the CLI).
I'll close the issue, but if it happens again feel free to comment with the log output and we'll see.

@whitedeviltakamachinanoha-oss It should mimic the Razor Sorround effect found on Windows. I'm not the author of the impulses files though, I just collected them around the web.
